#配置测试相关
configtest:
  v2:
    name: properties注入
    len: 222
    strlist:
      - str1
      - v2
      - lalal
  v3:
    name: springboot自动注入
    len: 333
    strlist:
      - kira
      - v3
      - ggggg

#端口
server:
  port: 8080

#日志
logging:
  level:
    priv.kira.springcloudtest.springboottest: info
    #priv.kira.springcloudtest.springboottest.controller: debug

#datasource
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springcloudtest
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver