server:
  port: 9010

spring:
  application:
    name: user-service
  #datasource
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springcloudtest
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

